<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\css\driverDetail.cs" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\css\driverDetail.cs" />
    <_ContentIncludedByDefault Remove="wwwroot\css\orderDetail.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\export-to-Excel.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture.Community.AutoMapper" Version="1.1.0" />
    <PackageReference Include="Bogus" Version="35.6.3" />
    <PackageReference Include="MediaBrowser.Common" Version="4.7.9" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.7.115">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="TweetinviAPI" Version="5.0.4" />
    <PackageReference Include="uikit" Version="2.25.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CNET_V7_Domain">
      <HintPath>CNET_V7_Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
